program: scripts/nqswap/run_selfcad.py
name: nqswap-greedy-self_cad_all_token
method: grid
metric:
  goal: maximize
  name: best_f1
parameters:
  cad_alpha:
    values: [0.25, 0.5, 1.0, 2.0, 4.0, 9.0]
  cad_beta:
    values: [0.0000001, 0.1, 0.2, 0.4, 0.5, 0.6, 0.8, 0.9]
command:
- "python"
- ${program}
- ${args}
- "--model_nm"
- "llama2-chat"
- "--decoding_algo"
- "self_cad_all_token"
- "--generation_config"
- "configs/greedy_config.json"
- "--data_file"
- "/home/ameya/ml-knowledge-conflicts/datasets/substitution-sets/MRQANaturalQuestionsTrain-corpus-substitution.jsonl"
- "--output_dir"
- "/home/ameya/grounded-decoding/outputs/nqswap/"
- "--n_samples"
- "500"
- "--shuffle_seed"
- "1704"
- "--log_wandb"